[Metadata]
Skin name=DESKTOP VU-METER 3
Version=3.9
Information=Audio Visualizer
Author=HiTBiT-PA
Website=http://hitbit-pa.deviantart.com/
License=Creative Commons Attribution - Non Commercial - Share Alike 3.0

[Rainmeter]
Update=32
ContextTitle=LOADER / PLAYER
ContextAction=!ToggleConfig "Desktop VU-Meter 3\Loader" "Loader.ini"
ContextTitle2=EXIT
ContextAction2=!DeactivateConfig "#CURRENTCONFIG#"
RightMouseUpAction=!SkinCustomMenu

[Variables]
@include=#@#Variables.inc

[MeasureAudioOutput]
Measure=Plugin
Plugin=AudioLevel
Port=Output
RMSAttack=#vRMSAttack#
RMSDecay=#vRMSDecay#
RMSGain=#vRMSGain#
PeakAttack=#vPeakAttack#
PeakDecay=#vPeakDecay#
PeakGain=#vPeakGain#

[MeasureAudioRMS_L]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=RMS

[MeasureAudioRMS_R]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=RMS

[MeasureAudioPeak_L]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Peak

[MeasureAudioPeak_R]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Peak

[MeasureLEDPeak_L]
Measure=Calc
Formula=MeasureAudioPeak_L
IfBelowValue=1
IfBelowAction=!HideMeter MeterLEDPeak_L
IfEqualValue=1
IfEqualAction=!ShowMeter MeterLEDPeak_L

[MeasureLEDPeak_R]
Measure=Calc
Formula=MeasureAudioPeak_R
IfBelowValue=1
IfBelowAction=!HideMeter MeterLEDPeak_R
IfEqualValue=1
IfEqualAction=!ShowMeter MeterLEDPeak_R

;

[VU-Meter1]
Meter=Image
X=0
Y=0
ImageName=#@#Images\analog\analog1.png

[VU-Meter2]
Meter=Image
X=126
Y=0
ImageName=#@#Images\analog\analog1.png

[TextL]
Meter=String
FontFace=Arial
FontColor=72,72,72
FontSize=8
StringStyle=Bold
StringAlign=Left
AntiAlias=1
X=56
Y=12
Text=L

[TextR]
Meter=String
FontFace=Arial
FontColor=72,72,72
FontSize=8
StringStyle=Bold
StringAlign=Left
AntiAlias=1
X=182
Y=12
Text=R

[MeterAudioRMS_L]
Meter=Roundline
MeasureName=MeasureAudioRMS_L
X=58
Y=79
LineLength=53
LineWidth=2
LineColor=20,20,20,255
StartAngle=4
RotationAngle=1.55
ControlAngle=1
AntiAlias=1

[MeterAudioRMS_Shadow_L]
Meter=Roundline
MeasureName=MeasureAudioRMS_L
X=53
Y=79
LineLength=45
LineWidth=2
LineColor=20,20,20,100
StartAngle=4
RotationAngle=1.55
ControlAngle=1
AntiAlias=1

[MeterAudioRMS_R]
Meter=Roundline
MeasureName=MeasureAudioRMS_R
X=184
Y=79
LineLength=53
LineWidth=2
LineColor=20,20,20,255
StartAngle=4
RotationAngle=1.55
ControlAngle=1
AntiAlias=1

[MeterAudioRMS_Shadow_R]
Meter=Roundline
MeasureName=MeasureAudioRMS_R
X=179
Y=79
LineLength=45
LineWidth=2
LineColor=20,20,20,100
StartAngle=4
RotationAngle=1.55
ControlAngle=1
AntiAlias=1

[MeterLEDPeak_L]
Meter=IMAGE
X=83
Y=35
ImageName=#@#Images\analog\peak.png
DynamicVariables=1
Hidden=1

[MeterLEDPeak_R]
Meter=IMAGE
X=209
Y=35
ImageName=#@#Images\analog\peak.png
DynamicVariables=1
Hidden=1
