[Metadata]
Skin name=DESKTOP VU-METER 3
Version=3.9
Information=Audio Visualizer
Author=HiTBiT-PA
Website=http://hitbit-pa.deviantart.com/
License=Creative Commons Attribution - Non Commercial - Share Alike 3.0

[Rainmeter]
Update=32
ContextTitle=LOADER / PLAYER
ContextAction=!ToggleConfig "Desktop VU-Meter 3\Loader" "Loader.ini"
ContextTitle2=EXIT
ContextAction2=!DeactivateConfig "#CURRENTCONFIG#"
RightMouseUpAction=!SkinCustomMenu

[Variables]
@include=#@#Variables.inc

[MeasureAudioOutput]
Measure=Plugin
Plugin=AudioLevel
Port=Output
RMSAttack=#vRMSAttack#
RMSDecay=#vRMSDecay#
RMSGain=#vRMSGain#

[MeasureRMS_L]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=RMS
IfCondition=MeasureRMS_L < 0.1
IfTrueAction=[!SetOption MeterFx_L ImageName "01.png"][!UpdateMeter *][!Redraw]
IfCondition2=(MeasureRMS_L > 0) && (MeasureRMS_L < 0.1332)
IfTrueAction2=[!SetOption MeterFx_L ImageName "02.png"][!UpdateMeter *][!Redraw]
IfCondition3=(MeasureRMS_L >= 0.1332) && (MeasureRMS_L < 0.1998)
IfTrueAction3=[!SetOption MeterFx_L ImageName "03.png"][!UpdateMeter *][!Redraw]
IfCondition4=(MeasureRMS_L >= 0.1998) && (MeasureRMS_L < 0.2664)
IfTrueAction4=[!SetOption MeterFx_L ImageName "04.png"][!UpdateMeter *][!Redraw]
IfCondition5=(MeasureRMS_L >= 0.2664) && (MeasureRMS_L < 0.3333)
IfTrueAction5=[!SetOption MeterFx_L ImageName "05.png"][!UpdateMeter *][!Redraw]
IfCondition6=(MeasureRMS_L >= 0.3333) && (MeasureRMS_L < 0.3996)
IfTrueAction6=[!SetOption MeterFx_L ImageName "06.png"][!UpdateMeter *][!Redraw]
IfCondition7=(MeasureRMS_L >= 0.3996) && (MeasureRMS_L < 0.4662)
IfTrueAction7=[!SetOption MeterFx_L ImageName "07.png"][!UpdateMeter *][!Redraw]
IfCondition8=(MeasureRMS_L >= 0.4662) && (MeasureRMS_L < 0.5328)
IfTrueAction8=[!SetOption MeterFx_L ImageName "08.png"][!UpdateMeter *][!Redraw]
IfCondition9=(MeasureRMS_L >= 0.5328) && (MeasureRMS_L < 0.5994)
IfTrueAction9=[!SetOption MeterFx_L ImageName "09.png"][!UpdateMeter *][!Redraw]
IfCondition10=(MeasureRMS_L >= 0.5994) && (MeasureRMS_L < 0.6666)
IfTrueAction10=[!SetOption MeterFx_L ImageName "10.png"][!UpdateMeter *][!Redraw]
IfCondition11=(MeasureRMS_L >= 0.6666) && (MeasureRMS_L < 0.7326)
IfTrueAction11=[!SetOption MeterFx_L ImageName "11.png"][!UpdateMeter *][!Redraw]
IfCondition12=(MeasureRMS_L >= 0.7326) && (MeasureRMS_L < 0.7992)
IfTrueAction12=[!SetOption MeterFx_L ImageName "12.png"][!UpdateMeter *][!Redraw]
IfCondition13=(MeasureRMS_L >= 0.7992) && (MeasureRMS_L < 0.8658)
IfTrueAction13=[!SetOption MeterFx_L ImageName "13.png"][!UpdateMeter *][!Redraw]
IfCondition14=(MeasureRMS_L >= 0.8658) && (MeasureRMS_L < 0.9324)
IfTrueAction14=[!SetOption MeterFx_L ImageName "14.png"][!UpdateMeter *][!Redraw]
IfCondition15=(MeasureRMS_L >= 0.9324) && (MeasureRMS_L >= 0.9999)
IfTrueAction15=[!SetOption MeterFx_L ImageName "15.png"][!UpdateMeter *][!Redraw]

[MeasureRMS_R]
Measure=Plugin
Plugin=AudioLevel
Parent=measureAudioOutput
Channel=R
Type=RMS
IfCondition=MeasureRMS_R < 0.1
IfTrueAction=[!SetOption MeterFx_R ImageName "01.png"][!UpdateMeter *][!Redraw]
IfCondition2=(MeasureRMS_R > 0) && (MeasureRMS_R < 0.1332)
IfTrueAction2=[!SetOption MeterFx_R ImageName "02.png"][!UpdateMeter *][!Redraw]
IfCondition3=(MeasureRMS_R >= 0.1332) && (MeasureRMS_R < 0.1998)
IfTrueAction3=[!SetOption MeterFx_R ImageName "03.png"][!UpdateMeter *][!Redraw]
IfCondition4=(MeasureRMS_R >= 0.1998) && (MeasureRMS_R < 0.2664)
IfTrueAction4=[!SetOption MeterFx_R ImageName "04.png"][!UpdateMeter *][!Redraw]
IfCondition5=(MeasureRMS_R >= 0.2664) && (MeasureRMS_R < 0.3333)
IfTrueAction5=[!SetOption MeterFx_R ImageName "05.png"][!UpdateMeter *][!Redraw]
IfCondition6=(MeasureRMS_R >= 0.3333) && (MeasureRMS_R < 0.3996)
IfTrueAction6=[!SetOption MeterFx_R ImageName "06.png"][!UpdateMeter *][!Redraw]
IfCondition7=(MeasureRMS_R >= 0.3996) && (MeasureRMS_R < 0.4662)
IfTrueAction7=[!SetOption MeterFx_R ImageName "07.png"][!UpdateMeter *][!Redraw]
IfCondition8=(MeasureRMS_R >= 0.4662) && (MeasureRMS_R < 0.5328)
IfTrueAction8=[!SetOption MeterFx_R ImageName "08.png"][!UpdateMeter *][!Redraw]
IfCondition9=(MeasureRMS_R >= 0.5328) && (MeasureRMS_R < 0.5994)
IfTrueAction9=[!SetOption MeterFx_R ImageName "09.png"][!UpdateMeter *][!Redraw]
IfCondition10=(MeasureRMS_R >= 0.5994) && (MeasureRMS_R < 0.6666)
IfTrueAction10=[!SetOption MeterFx_R ImageName "10.png"][!UpdateMeter *][!Redraw]
IfCondition11=(MeasureRMS_R >= 0.6666) && (MeasureRMS_R < 0.7326)
IfTrueAction11=[!SetOption MeterFx_R ImageName "11.png"][!UpdateMeter *][!Redraw]
IfCondition12=(MeasureRMS_R >= 0.7326) && (MeasureRMS_R < 0.7992)
IfTrueAction12=[!SetOption MeterFx_R ImageName "12.png"][!UpdateMeter *][!Redraw]
IfCondition13=(MeasureRMS_R >= 0.7992) && (MeasureRMS_R < 0.8658)
IfTrueAction13=[!SetOption MeterFx_R ImageName "13.png"][!UpdateMeter *][!Redraw]
IfCondition14=(MeasureRMS_R >= 0.8658) && (MeasureRMS_R < 0.9324)
IfTrueAction14=[!SetOption MeterFx_R ImageName "14.png"][!UpdateMeter *][!Redraw]
IfCondition15=(MeasureRMS_R >= 0.9324) && (MeasureRMS_R >= 0.9999)
IfTrueAction15=[!SetOption MeterFx_R ImageName "15.png"][!UpdateMeter *][!Redraw]

;

[MeterFx_L]
Meter=Image
X=0
Y=0
W=177
H=176
ImagePath=#@#Images\analog leds
ImageName=01.png
DynamicVariables=1

[MeterFx_R]
Meter=Image
X=190
Y=0
W=177
H=176
ImagePath=#@#Images\analog leds
ImageName=01.png
DynamicVariables=1

[TextL]
Meter=String
FontFace=Arial
FontColor=196,196,196
FontSize=10
StringStyle=Bold
StringAlign=Left
AntiAlias=1
X=115
Y=19
Text=L

[TextR]
Meter=String
FontFace=Arial
FontColor=196,196,196
FontSize=10
StringStyle=Bold
StringAlign=Left
AntiAlias=1
X=305
Y=19
Text=R
