[Metadata]
Skin name=DESKTOP VU-METER 3
Version=3.9
Information=Audio Visualizer
Author=HiTBiT-PA
Website=http://hitbit-pa.deviantart.com/
License=Creative Commons Attribution - Non Commercial - Share Alike 3.0

[Rainmeter]
Update=32
ContextTitle=LOADER / PLAYER
ContextAction=!ToggleConfig "Desktop VU-Meter 3\Loader" "Loader.ini"
ContextTitle2=EXIT
ContextAction2=!DeactivateConfig "#CURRENTCONFIG#"
RightMouseUpAction=!SkinCustomMenu

[Variables]
@include=#@#Variables.inc

[MeasureAudioOutput]
Measure=Plugin
Plugin=AudioLevel
Port=Output
RMSAttack=#vRMSAttack#
RMSDecay=#vRMSDecay#
RMSGain=#vRMSGain#

[MeasureAudioRMS_L]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=RMS

[MeasureAudioRMS_R]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=RMS

;

[VU-Meter1]
Meter=Image
X=0
Y=0
ImageName=#@#Images\analog\analog4.png

[VU-Meter2]
Meter=Image
X=200
Y=0
ImageName=#@#Images\analog\analog4.png

[TextL]
Meter=String
FontFace=Arial
FontColor=32,36,32
FontSize=8
StringStyle=Bold
StringAlign=Left
AntiAlias=1
X=8
Y=8
Text=L

[TextR]
Meter=String
FontFace=Arial
FontColor=32,36,32
FontSize=8
StringStyle=Bold
StringAlign=Left
AntiAlias=1
X=382
Y=8
Text=R

[MeterAudioRMS_L]
Meter=Roundline
MeasureName=MeasureAudioRMS_L
X=99
Y=99
LineLength=75
LineWidth=2
LineColor=20,20,20,255
StartAngle=3.65
RotationAngle=2.15
ControlAngle=1
AntiAlias=1

[MeterAudioRMS_Shadow_L]
Meter=Roundline
MeasureName=MeasureAudioRMS_L
X=95
Y=97
LineLength=67
LineWidth=2
LineColor=20,20,20,100
StartAngle=3.65
RotationAngle=2.15
ControlAngle=1
AntiAlias=1

[MeterAudioRMS_R]
Meter=Roundline
MeasureName=MeasureAudioRMS_R
X=299
Y=99
LineLength=75
LineWidth=2
LineColor=20,20,20,255
StartAngle=3.65
RotationAngle=2.15
ControlAngle=1
AntiAlias=1

[MeterAudioRMS_Shadow_R]
Meter=Roundline
MeasureName=MeasureAudioRMS_R
X=295
Y=97
LineLength=67
LineWidth=2
LineColor=20,20,20,100
StartAngle=3.65
RotationAngle=2.15
ControlAngle=1
AntiAlias=1
